### PR TITLE
NUT13-only Wallet with provided seed

### LINKED ISSUE #111: Use Xpriv in Wallet

### LINKED ISSUE #125: Wallet: Support only nut13 deterministic wallets
Currently both randomly generated secrets and NUT-13 derived secrets are supported. While the spec does not require supporting only NUT-13 doing so would reduce code complexity as the two options don't have to be handled separately. This change can also be made transparent to the lib user as if no secret is passed one can be generated for them, that they can choose to never use. Going this route leads to a more sensible default implementation of deterministic secrets allowing for CDK based wallets to be recovered by default instead of an extra feature as they are now.

### PR DESCRIPTION
**Pull request by davidcaseria**
The Wallet will now only support NUT -13-based secret derivation. The cdk user must provide a seed, which is used to generate an internal Xpriv.

Also, the database counter is changed to a u32 since the maximum value is `2^31-1`.

Closes #111 
Closes #125 
Relies on #126

### CODE REVIEW

**Comment by thesimplekid** [comment]
@davidcaseria Mind just rebaseing on main and squashing the commits. I can do it if not just let me know

**Review by thesimplekid — COMMENTED** [review]
Thanks for the PR looks good. Think just remove the feature and good to go

**Comment by davidcaseria** [comment]
I simplified your suggestion to a one-liner: `let count = count.map_or(0, |c| c + 1);`. I think that's still pretty clear if you know what the `map_or` function does, but let me know if you'd like me to change it to your suggestion.

**Comment by thesimplekid** [comment]
> I simplified your suggestion to a one-liner: let count = count.map_or(0, |c| c + 1);

Even better thanks

**Review by thesimplekid — APPROVED** [review]

**Pull request merged**
